scss/components/barriers/_barrier-grid.scss
scss/components/barriers/_main.scss
scss/components/barriers/_premium.scss
scss/components/barriers/_subscription-grid.scss
scss/components/barriers/_trial-grid.scss

This was hanging around when the barrier was an overlay.
Also helps with NFT-264
/cc @keirog @ironsidevsquincy

Remove z-index

---

scss/components/barriers/_main.scss
scss/components/barriers/_mobile.scss

Adds the styles for the mobile barrier

---

scss/components/barriers/_corporate.scss
scss/components/barriers/_main.scss

Add style overrides for custom corporate messaging

---

.gitignore
scss/components/barriers/_brexit-trial-grid.scss
scss/components/barriers/_main.scss

Initial brexit discount implementation

---

scss/components/barriers/_corporate-special.scss
scss/components/barriers/_main.scss

A temporary barrier to be shown when following links from the Rio hub.
https://github.com/Financial-Times/next-product-selector/pull/141

Rio Barrier

---

scss/components/barriers/_corporate-prospect-trial.scss
scss/components/barriers/_main.scss

Styling for the B2B prospect trial form barrier

B2B Styling

---

scss/components/barriers/_corporate-prospect-trial.scss

* Fixes for error and submission success pages

Corporate prospect trial copy and fixes

---

scss/components/barriers/_corporate-prospect-trial.scss

* Fixes issue with contact information positioning on desktop in Safari and Firefox

Corporate prospect trial barrier styling fixes

---

scss/components/barriers/_corporate-prominence.scss
scss/components/barriers/_main.scss
scss/components/barriers/_trial-grid.scss

New scss file for corporate prominence A/B test.
New control and a 5th column added to offers for variant.
(Feels super hacky, so any pointers to clean it up/different strategy welcome!)

Add corporate prominence

---

scss/components/barriers/_corporate-prominence.scss

US elections offers

---

scss/components/barriers/_premium.scss

DO NOT MERGE: Waiting on confirmation of design.

Increase bottom margin for subscribe link on premium barrier

---

scss/components/barriers/_trial-grid.scss

Reflect minor markup changes in next-product

---

bower.json

bump n-ui to v3

---

scss/components/barriers/_trial-grid.scss
scss/components/product-selector/main.scss

WIP: new secondary weekend-print option

---

scss/components/barriers/_inline.scss

Make the in article trial monthly text smaller

---

scss/components/barriers/_individual-b2b-prospect.scss

Add styling for sign in link

---

scss/components/barriers/_individual-b2b-prospect.scss

Fix the b2b barrier footers on mobile

---

scss/components/barriers/_individual-b2b-prospect.scss

* centered on mobile
* CTA button in header

style changes to individual b2b prospect

---

scss/_barrier.scss

🐿 v2.5.16
Updating focus color to **teal-100**.

teal focus update

---

scss/helpers/_util.scss

Add: new generic styling attributes for phantom-button
